# This script is used by Travis CI to run automatically Continuous test integration
# from ToManage ERP GitHub repository.
# For syntax, see https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

dist: trusty
sudo: required

language: node_js

# Start on every boot
services:
- redis-server
- mongodb

node_js:
  - "6"
  - "4"
 
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential graphicsmagick
  # Extract dump install database
  - sudo tar xzf dump/install.tgz -C tests/dump/
  # Restore demo database
  - mongorestore --port 27017 --db demo tests/dump/install/
  # Copy config file
  - sudo cp tests/config ./config
 
install:
  - npm install
  - npm install -g jshint
  - npm install -g eslint
  - npm install -g mocha

before_script:
- |
  echo Start travis
  echo Current dir is `pwd`
  echo Home dir is `echo ~`
  echo TRAVIS_BUILD_DIR is $TRAVIS_BUILD_DIR

script:
  - node debug.js &
  #- npm test
  - npm run test-jshint
  - npm run test-eslint
  - npm run test-mocha
